Numpy Array Operations

In [7]:
import numpy as np

In [8]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing ", arr[2:7])
print("With Step",arr[1:8:2])
print("Negative indexing",arr[-3])

Basic Slicing  [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 7


In [12]:
arr_2D=np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print("Specific element", arr_2D[1,2])

Specific element 6


In [13]:
print("Entire row",arr_2D[1])

Entire row [4 5 6]


In [14]:
print("Entire column",arr_2D[:,1])

Entire column [2 5 8]


Sorting

In [15]:
unsorted=np.array([3,1,5,9,6,2])
print("Sorted array",np.sort(unsorted))

Sorted array [1 2 3 5 6 9]


In [ ]:
arr_2d_unsorted=np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array row wise",np.sort(arr_2d_unsorted,axis=1))

Sorted 2D array [[1 3]
 [1 2]
 [2 3]]


In [18]:
arr_2d_unsorted=np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array column wise",np.sort(arr_2d_unsorted,axis=0))

Sorted 2D array column wise [[1 1]
 [2 2]
 [3 3]]


Filtering 


In [19]:
num=np.array([1,2,3,4,5,6,7,8,9,10])
even_number=num[num%2==0]
print("Even Numbers",even_number)

Even Numbers [ 2  4  6  8 10]


Filter with mask

In [20]:
mask=num>5
print("Number grater than 5",num[mask])

Number grater than 5 [ 6  7  8  9 10]


Fancy Indexing vs np.where()

In [22]:
indices=[0,2,4]
print(num[indices])

where_result=np.where(num>5)
print(where_result)
print("NP where",num[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [26]:
condition_array=np.where(num>5,num*2,num)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


Adding and Removing Data

In [27]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

combined=np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


Array Compatibility

In [29]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])

print("Compatibility shapes",a.shape==b.shape)

Compatibility shapes True


In [33]:
original=np.array([[1,2] ,[3,4]])
new_row=np.array([[5,6]])

with_new_row=np.vstack((original,new_row))
print(original)
print(with_new_row)

new_col=np.array([[7],[8]])
with_new_col=np.hstack((original,new_col))
print("With new column",with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column [[1 2 7]
 [3 4 8]]


In [35]:
arr=np.array([1,2,3,4,5,6])
deleted=np.delete(arr,2)
print("Array after deletion",deleted)

Array after deletion [1 2 4 5 6]
