Numpy Baics and Array


In [2]:
import numpy as np

Creating  array from List


In [3]:
arr_1d=np.array([1, 2, 3, 4, 5])
print("1D array",arr_1d)

arr_2d=np.array([[1,2,3], [4,5,6]])
print("2D array",arr_2d)

1D array [1 2 3 4 5]
2D array [[1 2 3]
 [4 5 6]]


List VS Numpy Array

In [6]:
py_list=[1,2,3,4]
print("Python list multiplication", py_list*2)


np_array=np.array([1,2,3])
print("Python numpy array multiplication ",np_array*2)

Python list multiplication [1, 2, 3, 4, 1, 2, 3, 4]
Python numpy array multiplication  [2 4 6]


Import Time Module

In [8]:
import time
start=time.time()
py_list=[i*2 for i in range(100000)]
print("\n List operation time  ",time.time()-start)


start =time.time()
np_array=np.arange(100000)*2
print("\n Numpy operation time ",time.time()-start)


 List operation time   0.010216474533081055

 Numpy operation time  0.004170894622802734


Creating Array from Scratch

In [9]:
zeros=np.zeros((3,4))
print("zeros array :",zeros)

zeros array : [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
ones=np.ones((3,4))
print("ones array :",ones)

ones array : [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
full=np.full((2,2),7)
print("full array :",full)

full array : [[7 7]
 [7 7]]


Import Random Module

In [12]:
random=np.random.random((2,3))
print("random array :\n",random)

random array :
 [[0.82072477 0.64902369 0.52100254]
 [0.96406456 0.75191234 0.32196185]]


In [13]:
sequence=np.arange(0,12,2)
print("sequence array \n" ,sequence)

sequence array 
 [ 0  2  4  6  8 10]


Vector Matrix and Tensor

In [14]:
vector=np.array([1,2,3,4,5])
print("Vector :",vector)

matrix=np.array([[1,2,3,4],
                [4,5,6,7]])
print("Mtrix :",matrix)

tensor=np.array([[[1,2],[3,4]],
                 [[4,5],[8,9]]])
print("Tensor :",tensor)

Vector : [1 2 3 4 5]
Mtrix : [[1 2 3 4]
 [4 5 6 7]]
Tensor : [[[1 2]
  [3 4]]

 [[4 5]
  [8 9]]]


Array Properties

In [15]:
arr=np.array([[1,2,3,4],
             [5,6,7,8]])
print("Shape :",arr.shape)
print("Dimension :",arr.ndim)
print("Size :",arr.size)
print("Dtype :",arr.dtype)


Shape : (2, 4)
Dimension : 2
Size : 8
Dtype : int64


Reshaping of Array

In [16]:
arr=np.arange(15)
print("Original array : ",arr)

reshaped=arr.reshape((3,5))
print("\n Reshaped Array :",reshaped)

flattened=reshaped.flatten()
print("\n Flattened Array :", flattened)

#Revel (return view original array ,instead of copy)
reveled= reshaped.ravel()
print("\n reveled array :",reveled)

Original array :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

 Reshaped Array : [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

 Flattened Array : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

 reveled array : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


Transpose

In [17]:
transpose=reshaped.T
print("\n Transpose array :",transpose)


 Transpose array : [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
