NumPy (Intermediate)
 An HR system stores employee performance ratings (scale 1–5) for 100 employees over 4 quarters in a NumPy array.
 
Task:
Normalize the ratings using min-max normalization


Calculate the average rating per employee


Identify employees whose average rating is above the company mean




In [4]:
import numpy as np

In [6]:
np.random.seed(45)

In [7]:
ratings=np.random.randint(1,6,size=(100,4))

In [9]:
re_min=ratings.min()
re_max=ratings.max()
normalization_ratings=(ratings-re_min)/(re_max-re_min)
print(normalization_ratings)

[[0.75 0.75 1.   0.  ]
 [0.75 1.   0.25 0.  ]
 [0.25 0.25 0.   0.  ]
 [1.   0.5  1.   0.  ]
 [1.   0.25 1.   0.  ]
 [0.5  1.   1.   0.25]
 [0.25 1.   0.5  0.75]
 [0.   0.   0.25 0.75]
 [0.75 0.5  0.   1.  ]
 [0.25 0.   0.   0.25]
 [0.5  0.75 0.   0.  ]
 [0.75 0.5  0.5  1.  ]
 [0.25 0.5  0.   0.25]
 [0.   0.   0.   0.  ]
 [0.75 1.   0.   0.75]
 [0.25 0.75 1.   0.25]
 [0.75 0.75 0.5  1.  ]
 [0.25 0.25 0.25 0.75]
 [0.25 1.   0.5  0.5 ]
 [0.25 1.   0.75 1.  ]
 [1.   0.25 0.5  0.75]
 [0.75 0.75 0.   1.  ]
 [1.   0.25 0.75 0.5 ]
 [0.75 0.25 0.   0.5 ]
 [0.75 0.75 0.25 0.75]
 [0.25 1.   1.   0.5 ]
 [0.5  0.75 0.25 0.75]
 [0.75 0.25 0.25 0.25]
 [1.   0.   0.5  0.5 ]
 [0.25 0.5  1.   0.25]
 [1.   0.5  0.5  0.75]
 [0.5  0.75 0.5  0.75]
 [0.75 0.75 1.   0.5 ]
 [0.   0.5  0.25 0.5 ]
 [1.   0.25 1.   1.  ]
 [0.75 1.   0.75 0.5 ]
 [1.   0.25 0.75 0.  ]
 [0.75 1.   0.   0.5 ]
 [1.   0.   0.75 1.  ]
 [0.5  0.   0.25 0.25]
 [0.25 0.5  1.   1.  ]
 [0.   0.   0.5  0.  ]
 [0.25 1.   1.   1.  ]
 [0.75 0.5 

In [15]:
average_ratings_per_employee=normalization_ratings.mean(axis=1)
print(average_ratings_per_employee)

[0.625  0.5    0.125  0.625  0.5625 0.6875 0.625  0.25   0.5625 0.125
 0.3125 0.6875 0.25   0.     0.625  0.5625 0.75   0.375  0.5625 0.75
 0.625  0.625  0.625  0.375  0.625  0.6875 0.5625 0.375  0.5    0.5
 0.6875 0.625  0.75   0.3125 0.8125 0.75   0.5    0.5625 0.6875 0.25
 0.6875 0.125  0.8125 0.625  0.375  0.25   0.625  0.4375 0.625  0.4375
 0.125  0.625  0.5    0.3125 0.5    0.625  0.5    0.5    0.6875 0.4375
 0.5625 0.6875 0.4375 0.6875 0.3125 0.5625 0.625  0.6875 0.375  0.125
 0.5    0.5    0.125  0.3125 0.1875 0.5625 0.625  0.5    0.1875 0.3125
 0.625  0.3125 0.75   0.1875 0.5    0.5    0.4375 0.6875 0.125  0.5625
 0.5    0.625  0.75   0.8125 0.5625 0.5625 0.375  0.5625 0.3125 0.625 ]


In [24]:
company_mean=normalization_ratings.mean()
print(company_mean)

0.500625


In [25]:
top_employee=np.where(average_ratings_per_employee>company_mean)[0]

In [26]:
print(top_employee)

[ 0  3  4  5  6  8 11 14 15 16 18 19 20 21 22 24 25 26 30 31 32 34 35 37
 38 40 42 43 46 48 51 55 58 60 61 63 65 66 67 75 76 80 82 87 89 91 92 93
 94 95 97 99]
