NumPy (Intermediate)
 An online platform tracks time spent (in minutes) by students on 6 courses over 14 days using a NumPy array.
 
Task:
Compute total time spent per course


Identify courses where average daily engagement exceeds a threshold


Rank courses based on engagement


In [1]:
import numpy as np

In [2]:
np.random.seed(50)

In [11]:
track_time=np.random.randint(10,120,size=(6,14))
print("Time spend on course in 14 days  ",track_time)

Time spend on course in 14 days   [[ 97  42  29  57  79 102  16  75  46  94  46  54  63  88]
 [ 14  96  53  29 106  47 114  40  72  54  53  45 112  37]
 [ 60  68  38  41 114  25  15  62  65  66  57  78  14  28]
 [ 52  27 100  82  56  21  37  37  69  17  51  75  63  82]
 [ 45  13  31  52  77  80  66  89 105  32  10  66  85  40]
 [ 43  24 100  32  56 111  16  72  40 115  46  67 105  19]]


In [12]:
total_time=track_time.sum(axis=1)

In [13]:
print("Time spend to complete one course",total_time)

Time spend to complete one course [888 872 731 769 791 846]


In [14]:
threshold=60
average_daily_engagment=np.mean(track_time,axis=1)
print("The Average time ",average_daily_engagment)

The Average time  [63.42857143 62.28571429 52.21428571 54.92857143 56.5        60.42857143]


In [15]:
exceeds_threshold_mask=average_daily_engagment>threshold
course_exceeding=np.where(exceeds_threshold_mask)[0]
print(course_exceeding)


[0 1 5]


In [16]:
course_ranking=total_time.argsort()[::-1]
print("Ranking of courses from 0 to 5",course_ranking)

Ranking of courses from 0 to 5 [0 1 5 4 3 2]
