 A retail company records daily sales of 5 products across 30 days in a 2D NumPy array of shape (30, 5).

 Due to a system error, negative values appear in the dataset.

Task:
Replace negative values with 0

Compute the average weekly sales per product (assume 7 days = 1 week)

Identify the product with the highest average weekly sales


In [2]:
import numpy as np

In [3]:
np.random.seed(50)

In [4]:
sales_data=np.random.randint(-50,500,size=(30,5))

In [5]:
print(sales_data[:10])

[[430  59 239  82  20]
 [179  20 228  83 208]
 [ 45 200  21 317 402]
 [113 104 168  84 354]
 [291  56 270 457 468]
 [ 97  29 364  55 369]
 [449 -24 321  80 -50]
 [ 43 171 -50  89   1]
 [106 102  41 124  12]
 [498  78 136 353  -5]]


In [6]:
sales_data[sales_data<0]=0

In [7]:
print(sales_data[:10])

[[430  59 239  82  20]
 [179  20 228  83 208]
 [ 45 200  21 317 402]
 [113 104 168  84 354]
 [291  56 270 457 468]
 [ 97  29 364  55 369]
 [449   0 321  80   0]
 [ 43 171   0  89   1]
 [106 102  41 124  12]
 [498  78 136 353   0]]


In [16]:
weekly_sales=sales_data[:28].reshape(4,7,5)
print(weekly_sales)

[[[430  59 239  82  20]
  [179  20 228  83 208]
  [ 45 200  21 317 402]
  [113 104 168  84 354]
  [291  56 270 457 468]
  [ 97  29 364  55 369]
  [449   0 321  80   0]]

 [[ 43 171   0  89   1]
  [106 102  41 124  12]
  [498  78 136 353   0]
  [161 335 258 377  51]
  [293 238 459 147  42]
  [114 290   0 250 259]
  [  0 292 225 174 396]]

 [[121 241 436   0 454]
  [365 467 200 386 389]
  [331 262  18 338 352]
  [  0 406 124 105 361]
  [469 375 259  81 227]
  [376 401  20 301 206]
  [  6 448 364 331 476]]

 [[296  67  12   0 183]
  [  7 204 343  14   8]
  [447 190 104  82 143]
  [  0  92 390 208 356]
  [436 457 284   0 123]
  [139 261  28  97 126]
  [191 412   0 489 178]]]


In [17]:
weekly_totals=weekly_sales.sum(axis=1)
print(weekly_totals)

[[1604  468 1611 1158 1821]
 [1215 1506 1119 1514  761]
 [1668 2600 1421 1542 2465]
 [1516 1683 1161  890 1117]]


In [18]:
average_weekly_sales=weekly_totals.mean(axis=0)
print(average_weekly_sales)

[1500.75 1564.25 1328.   1276.   1541.  ]


In [19]:
best_product=np.argmax(average_weekly_sales)
print(best_product+1)

2
